version: '3.2'

services: 
  python:
    image: scraping/python:1.0
    build: ./python
    container_name: 'scraping_python'
    stdin_open: true
    tty: true
    volumes: 
      - ../python:/home/user1/dev